### ISSUE TITLE
Fillet Button Not working - No Response

### ISSUE THREAD

**Issue by MrLRichards** [Clockmender/Precision-Drawing-Tools#22] opened 2020-09-06 00:48 UTC
**Describe the bug**

There is no response when clicking the Fillet button.

**To Reproduce**
Following the the Example 1 here: https://github.com/Clockmender/Precision-Drawing-Tools/wiki/06-PDT-Design;-Tools 
Fillet subsection.

**Expected behavior**

I was expecting to see the vertices become a Fillet with 6 segments with a 0.5 radius.

**Screenshots**

There are no error messages or anything. There is simply no response.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Chrome: Version 85.0.4183.83 (Official Build) (64-bit)

**Additional context**

Blender 2.90.0
PDT 1.4.0

Downloaded and installed PDT v1.4.1 and the same issue remains.
Units | Length | millimeters
Unit | Scale | 0.0010000
These settings are in reference to following:
Maker Tales
https://www.youtube.com/watch?v=ZI49VIcISaw  and
https://www.youtube.com/watch?v=CIcvA5B-N3U

I was able to see the Fillet tool function as it should in Blender 2.83.5. So at this point it seems the issue for me only exists in Blender 2.90.0.

**Comment by Clockmender** [comment] 2020-09-06 18:08
OK, I cannot reproduce this on Mac, can you tell me whether you are trying to fillet an edge loop, or edges of a 3D shape, because it matters whether you use the "Use Vertices" checkbox, or not. Check this box if you want to add a fillet at a vertex, don't check it if you want to fillet the edges of a 3D shape.

Option 1, Fillet a corner of a 2D shape:

<img width="728" alt="Screenshot 2020-09-06 at 19 04 39" src="https://user-images.githubusercontent.com/29657804/92332219-004adc00-f074-11ea-9adb-4df8a8d2e558.png">

Option 2, Fillet a corner of a 3D shape:

<img width="798" alt="Screenshot 2020-09-06 at 19 05 31" src="https://user-images.githubusercontent.com/29657804/92332223-0fca2500-f074-11ea-8b4e-ecb37a740af2.png">

Let me know exactly what you are doing and whether you are using Vertex, or Edge Fillets please.

Cheers, Clock.

**Comment by MrLRichards** [comment] 2020-09-06 19:23
I am attempting to fillet a vertices on a 2D shape. So, User Vertices checkbox is checked. I have the Radius set to 2.5mm | Segments set to 4 | Profile set to 1.00.

Vertices selected, I click the Fillet button and nothing happens. There are no messages to provide. I do have Enable console debug output from PDT scripts enabled.

![Vetices](https://user-images.githubusercontent.com/37518788/92333605-dd5cff80-f054-11ea-8f46-258c41860b71.PNG)

Thanks, Lewis

**Comment by Clockmender** [comment] 2020-09-06 19:28
Profile should be set to **0.5** for a circular fillet - 1.0 mean straight fillet so nothing happens...

<img width="923" alt="Screenshot 2020-09-06 at 20 27 16" src="https://user-images.githubusercontent.com/29657804/92333694-6db03a00-f07f-11ea-9a33-bbe979d440c4.png">

**Comment by MrLRichards** [comment] 2020-09-06 19:31
I have tried with  Profile set to 0.50 and still no response. The Fillet button turns orange when pressed but nothing happens. Can't capture that.

**Comment by Clockmender** [comment] 2020-09-06 19:35
OK, it's late Sunday night here, so I'll look again tomorrow. I can't reproduce your error (as you can see above), so I need to try to find another possible reason.

**Comment by MrLRichards** [comment] 2020-09-06 19:38
I have removed a edge and when selecting 2 vertices, the status shows that I have 3 selected. However when I select one at a time, status there is only 1 selected. The problem may be here somewhere. Have a good night.

**Comment by MrLRichards** [comment] 2020-09-06 19:42
However, I merged the hidden vert and the issue remains.
![Vetices3](https://user-images.githubusercontent.com/37518788/92333936-5198a280-f057-11ea-922c-54d12a35e94a.PNG)

**Comment by Clockmender** [comment] 2020-09-07 08:52
OK, I have just taken the latest 2.90 and found that the Bevel operation I use has changed in the API, so I need to rework this, and probably a lot more besides... Leave it with me, I will look into it today.

Error:

<img width="691" alt="Screenshot 2020-09-07 at 09 51 47" src="https://user-images.githubusercontent.com/29657804/92368555-c9b2a700-f0ef-11ea-8709-99631b9002bc.png">

Cheers, Clock.

**Comment by Clockmender** [comment] 2020-09-07 09:07
OK, I have fixed that on my system, I will need to check a lot more things before I make any update version...

<img width="776" alt="Screenshot 2020-09-07 at 10 06 02" src="https://user-images.githubusercontent.com/29657804/92370184-dc2de000-f0f1-11ea-98eb-55019d554347.png">

This is going to take a while to check every change in the API.

**Comment by MrLRichards** [comment] 2020-09-07 12:24
This is great news! I am glad you were able to find it. I will patiently
wait for the next revision.
Still learning Python, would love to get into helping the community making
add-ons and such.
Thanks for a great tool. I also design furniture and really like doing so
in Blender. When I found the tutorial on Youtube and the introduction to
PDT, I got very excited.

Lewis

**Comment by Jordywordy** [comment] 2020-09-21 16:02
Good day chief, has there been a fix to the bug yet?

**Comment by MrLRichards** [comment] 2020-09-21 16:05
As far as I know, the answer is no. However, I was told that it will be a
while due to the number of changes made to the API.

**Comment by Clockmender** [comment] 2020-09-21 18:22
I have finished the mods and checked everything thoroughly, just waiting for the release to be cut then we are good to go.

Cheers, Clock.

**Comment by MrLRichards** [comment] 2020-09-21 21:26
That's great news Alan and sooner than I was expecting. Excited for the new
release. Thanks from all of us!

Kind regards,

Lewis

**Comment by MrLRichards** [comment] 2020-09-21 21:26
Just got news that a new release is coming real soon.

Kind regards,

Lewis

**Comment by Clockmender** [comment] 2020-09-29 10:53
Fixed in latest release for Blender 2.90, see this:

https://github.com/Clockmender/Precision-Drawing-Tools/releases

Cheers, Clock.

**Comment by MrLRichards** [comment] 2020-09-29 15:37
Thank you so much, Clock for knocking that out!

Cheers, Lewis

**Comment by fahadtv008** [comment] 2020-11-20 10:16
great to see the bug fix for blender 2.9
there is one more issue regarding value for the radius
that is, the radius for fillets remains the same for different values of input radius

**Comment by Clockmender** [comment] 2020-11-20 14:18
OK @fahadtv008, I canot reproduce your error:

<img width="804" alt="Screenshot 2020-11-20 at 13 59 50" src="https://user-images.githubusercontent.com/29657804/99810017-0876cb80-2b3b-11eb-9c27-20fdafefeb58.png">

<img width="793" alt="Screenshot 2020-11-20 at 14 00 10" src="https://user-images.githubusercontent.com/29657804/99810028-0c0a5280-2b3b-11eb-830d-f9f1e03847ee.png">

Can you give me more information, such as operating system, version of Blender, blend file setup, anything to help me! Maybe upload your blend file for me to look at...

Cheers, Clock.

**Comment by fahadtv008** [comment] 2020-11-21 10:40
thank you for your response
sorry i got it right after restarting the blender file
now every thing is alright

**Closed** 2020-11-22 10:39 UTC
Labels: bug
